## Import all the things

In [13]:
import pandas as pd

## Read the dataframe

In [14]:
df = pd.read_csv("/Users/shabha/Downloads/20180504_194820.csv")

In [18]:
df.head()

,Day,Publisher ID,Site ID,Section ID,Ads Requested,Ads Returned,CTR,Clicks,Conversions,Fill Rate,...,Video 25% Rate,Video 50% Complete,Video 50% Rate,Video 75% Complete,Video 75% Rate,Video Start Rate,Video Starts,Video View Rate,Video Views,eCPM
0,2018-05-01,959242,11790,5533663,8880629450,467401550,0.000503,5049,0,0.052632,...,0.0,0,0.0,0,0.0,0.0,0,0.0,0,0.948750
1,2018-04-30,959242,11790,5533663,8852479848,465919992,0.000534,4845,0,0.052632,...,0.0,0,0.0,0,0.0,0.0,0,0.0,0,0.953319
2,2018-05-02,959242,11790,5533663,8693395964,457547156,0.000500,5043,0,0.052632,...,0.0,0,0.0,0,0.0,0.0,0,0.0,0,0.904894
3,2018-05-03,959242,11790,5533663,8522951790,448576410,0.000494,4693,0,0.052632,...,0.0,0,0.0,0,0.0,0.0,0,0.0,0,0.879871
4,2018-04-27,959242,11790,5533663,7681833019,404307001,0.000516,3248,0,0.052632,...,0.0,0,0.0,0,0.0,0.0,0,0.0,0,1.037137

In [19]:
## add impression_fill_rate impressions/add_requested

In [20]:
df['Impression Fill Rate'] = df['Impressions']/df['Ads Returned']

In [22]:
df.head()

,Day,Publisher ID,Site ID,Section ID,Ads Requested,Ads Returned,CTR,Clicks,Conversions,Fill Rate,...,Video 50% Complete,Video 50% Rate,Video 75% Complete,Video 75% Rate,Video Start Rate,Video Starts,Video View Rate,Video Views,eCPM,Impression Fill Rate
0,2018-05-01,959242,11790,5533663,8880629450,467401550,0.000503,5049,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.948750,0.021484
1,2018-04-30,959242,11790,5533663,8852479848,465919992,0.000534,4845,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.953319,0.019482
2,2018-05-02,959242,11790,5533663,8693395964,457547156,0.000500,5043,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.904894,0.022052
3,2018-05-03,959242,11790,5533663,8522951790,448576410,0.000494,4693,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.879871,0.021176
4,2018-04-27,959242,11790,5533663,7681833019,404307001,0.000516,3248,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,1.037137,0.015560

In [23]:
import matplotlib.pyplot as plt

In [24]:
pd.options.display.mpl_style = 'default'

OptionError: 'You can only set the value of existing options'

In [25]:
df.head()

,Day,Publisher ID,Site ID,Section ID,Ads Requested,Ads Returned,CTR,Clicks,Conversions,Fill Rate,...,Video 50% Complete,Video 50% Rate,Video 75% Complete,Video 75% Rate,Video Start Rate,Video Starts,Video View Rate,Video Views,eCPM,Impression Fill Rate
0,2018-05-01,959242,11790,5533663,8880629450,467401550,0.000503,5049,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.948750,0.021484
1,2018-04-30,959242,11790,5533663,8852479848,465919992,0.000534,4845,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.953319,0.019482
2,2018-05-02,959242,11790,5533663,8693395964,457547156,0.000500,5043,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.904894,0.022052
3,2018-05-03,959242,11790,5533663,8522951790,448576410,0.000494,4693,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,0.879871,0.021176
4,2018-04-27,959242,11790,5533663,7681833019,404307001,0.000516,3248,0,0.052632,...,0,0.0,0,0.0,0.0,0,0.0,0,1.037137,0.015560

In [26]:
df['Impression Fill Rate'] = df['Impressions']/df['Ads Returned']

In [27]:
df = df[['Impression Fill Rate','eCPM','CTR']]

In [28]:
df.boxplot()

NameError: name '_converter' is not defined